name: RDP

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Downloading & Installing
        run: |
          https://raw.githubusercontent.com/AyushDevTools/AutoSetup/main/Downloads.bat

      - name: Show Website
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
